#!/usr/bin/env node

// BMI1/BMI2/ADX and random-instruction flag tests for both 64-bit engines.
//
// Harness rules:
//   * Encodings come from a clang assemble/objdump round trip, never from
//     hand-written VEX bytes or from reading the VEX fields by eye. Operand
//     roles are read off that disassembly, which prints sources first.
//   * The harness verifies its own register read-back before trusting results.
//   * Memory-operand forms get their own cases; the register form exercises a
//     different decode path and would not notice a broken memory read.
//
// Requires a debug wasm build: `make build/v64-debug.wasm`
// Run with: `node tests/jit64/bmi1.js`
//
// Encodings, from:
//   clang -target x86_64-unknown-linux-gnu -march=haswell -c  &&  objdump -d
//     andnq  %rax, %rbx, %rcx   c4 e2 e0 f2 c8
//     andnq  (%r15), %rbx, %rcx c4 c2 e0 f2 0f
//     bextrq %rax, %rbx, %rcx   c4 e2 f8 f7 cb
//     blsiq  %rax, %rbx         c4 e2 e0 f3 d8
//     blsmskq %rax, %rbx        c4 e2 e0 f3 d0
//     blsrq  %rax, %rbx         c4 e2 e0 f3 c8
//     mulxq  %rax, %rbx, %rcx   c4 e2 e3 f6 c8
//     sarxq  %rax, %rbx, %rcx   c4 e2 fa f7 cb
//     rorxq  $0x5, %rax, %rbx   c4 e3 fb f0 d8 05
//     rorxl  $0x5, %eax, %ebx   c4 e3 7b f0 d8 05
//     adcxq  %rax, %rcx         66 48 0f 38 f6 c8
//     adoxq  %rax, %rcx         f3 48 0f 38 f6 c8
//     adcx   %eax, %ecx         66 0f 38 f6 c8
//     mulxq  (%r15), %rbx, %rcx c4 c2 e3 f6 0f
//
// Operand roles, read off that disassembly (AT&T prints sources first):
//   andnq  %rax, %rbx, %rcx -> dst=rcx (ModRM.reg), src1=rbx (VEX.vvvv),
//                                src2=rax (rm)
//   bextrq %rax, %rbx, %rcx -> dst=rcx, ctrl=rax (VEX.vvvv), src=rbx (rm)
//   blsiq  %rax, %rbx       -> dst=rbx (VEX.vvvv), src=rax (rm)
//   mulxq  %rax, %rbx, %rcx -> hi=rcx (ModRM.reg), lo=rbx (VEX.vvvv),
//                                and the multiplier is rax (rm)
//   sarxq  %rax, %rbx, %rcx -> dst=rcx, src=rbx (rm), count=rax (VEX.vvvv)
//   rorxq  $n, %rax, %rbx   -> dst=rbx (ModRM.reg), src=rax (rm)
//   adcxq  %rax, %rcx       -> dst=rcx (ModRM.reg), src=rax (rm)
//   mulxq  (%r15), %rbx, %rcx -> multiplier=[r15] (rm), multiplicand=rdx (implicit)
//
// RDRAND / RDSEED, from `clang -target x86_64-unknown-linux-gnu -c && objdump -d`:
//   rdrandq %rax   48 0f c7 f0      rdseedq %rbx   48 0f c7 fb
//   rdrandl %eax   0f c7 f0         rdseedl %ebx   0f c7 fb
//   rdrandw %ax    66 0f c7 f0      rdseedw %bx    66 0f c7 fb
//   rdseedq %r12   49 0f c7 fc      rdrandq %r13   49 0f c7 f5
//
// BMI1 instructions require VEX; the corresponding legacy slots raise #UD.
//
// The counts above are the ones the cases with a distinctive value use. The
// rest differ only in the immediate, and are listed here as generated by
// objdump so that tests/vex-encoding-check.py covers every hand-written byte
// string in this file: an encoding absent from the tables is one nobody has
// vouched for.
//   rorxq 0x0,rax,rbx    c4 e3 fb f0 d8 00
//   rorxq 0x3f,rax,rbx    c4 e3 fb f0 d8 3f
//   rorxq 0x20,rax,rbx    c4 e3 fb f0 d8 20
//   rorxl 0x0,eax,ebx    c4 e3 7b f0 d8 00
//   rorxl 0x1f,eax,ebx    c4 e3 7b f0 d8 1f
//   rorxl 0x21,eax,ebx    c4 e3 7b f0 d8 21
import { v64 } from "../../src/main.js";
import { set_cpu_config, JIT_DISABLE_64 } from "../../src/config.js";

const BASE = 0x1000;
// Staging area for memory-operand cases; r15 points here.
const SCRATCH = 0x100000;
const PML4 = 0x10000;
const PDPT = 0x11000;
const PD = 0x12000;
const PT = 0x13000;

// Register names used in the case tables, mapped to the emulator's indices.
const REG = { rax: 0, rcx: 1, rdx: 2, rbx: 3, rsp: 4, rbp: 5, rsi: 6, rdi: 7 };

// EFLAGS bit positions for the six arithmetic flags RDRAND/RDSEED write.
const FLAG_BIT = { cf: 1 << 0, pf: 1 << 2, af: 1 << 4, zf: 1 << 6, sf: 1 << 7, of: 1 << 11 };
const ARITH_FLAGS = Object.keys(FLAG_BIT);
// The flags the SDM says RDRAND/RDSEED zero. CF is not here: it reports whether
// a value was produced, which the reference model always takes as success.
const ZEROED_BY_RDRAND = ARITH_FLAGS.filter(f => f !== "cf");

const M = 0xFFFFFFFFFFFFFFFFn;
const u64 = v => BigInt.asUintN(64, v);

const CASES = [
    {
        // dst = ~src1 & src2.  src1=0x0F, src2=0xFF:
        //   correct  ->  ~0x0F & 0xFF = 0xF0
        //   swapped  ->  ~0xFF & 0x0F = 0x00
        //   no NOT   ->  src1 & src2  = 0x0F
        name: "andnq: dst = ~src1 & src2",
        code: [0xC4, 0xE2, 0xE0, 0xF2, 0xC8],
        set: { rax: 0xFFn, rbx: 0x0Fn, rcx: 0n },
        check: { reg: 1, want: 0xF0n },
    },
    {
        name: "andnq: second operand set",
        code: [0xC4, 0xE2, 0xE0, 0xF2, 0xC8],
        set: { rax: 0x0Fn, rbx: 0xFFn, rcx: 0n },
        check: { reg: 1, want: 0x00n },
    },
    {
        // BEXTR: start = ctrl[7:0], len = ctrl[15:8], bits taken from src (rm).
        // dst = ModRM.reg (rcx), ctrl = VEX.vvvv (rax), src = rm (rbx).
        // The control word is len << 8 | start, so start=32 len=16 is 0x1020;
        // writing 0x100020 here silently sets len = 0, which extracts nothing.
        name: "bextrq: start 32 len 16",
        code: [0xC4, 0xE2, 0xF8, 0xF7, 0xCB],
        // 0x1122334455667788 >> 32 = 0x11223344, low 16 bits = 0x3344
        // (0x5566 would be bits 16..31, i.e. start=16).
        set: { rbx: 0x1122334455667788n, rax: 0x1020n },
        check: { reg: 1, want: 0x3344n },
    },
    {
        name: "bextrq: start 0 len 32",
        code: [0xC4, 0xE2, 0xF8, 0xF7, 0xCB],
        set: { rbx: 0x1122334455667788n, rax: 0x2000n },
        check: { reg: 1, want: 0x55667788n },
    },
    {
        // BLSI: isolate the lowest set bit.
        name: "blsiq: lowest set bit",
        code: [0xC4, 0xE2, 0xE0, 0xF3, 0xD8],
        set: { rax: 0x0F0F0F0F0F0F0F0Fn },
        check: { reg: 3, want: 1n },
    },
    {
        name: "blsiq: 0 -> 0",
        code: [0xC4, 0xE2, 0xE0, 0xF3, 0xD8],
        set: { rax: 0n },
        check: { reg: 3, want: 0n },
    },
    {
        // BLSMSK: every bit from 0 up to and including the highest set bit.
        // 0x0F0F... has its top set bit at 59, so the mask is 0x0FFF...FF.
        name: "blsmskq",
        code: [0xC4, 0xE2, 0xE0, 0xF3, 0xD0],
        set: { rax: 0x0F0F0F0F0F0F0F0Fn },
        check: { reg: 3, want: 0x0FFFFFFFFFFFFFFFn },
    },
    {
        name: "blsmskq: 0 -> 0",
        code: [0xC4, 0xE2, 0xE0, 0xF3, 0xD0],
        set: { rax: 0n },
        check: { reg: 3, want: 0n },
    },
    {
        name: "blsmskq: single low bit",
        code: [0xC4, 0xE2, 0xE0, 0xF3, 0xD0],
        set: { rax: 1n },
        check: { reg: 3, want: 1n },
    },
    {
        // BLSR: clear the lowest set bit.
        name: "blsrq",
        code: [0xC4, 0xE2, 0xE0, 0xF3, 0xC8],
        set: { rax: 0x0F0F0F0F0F0F0F0Fn },
        check: { reg: 3, want: 0x0F0F0F0F0F0F0F0En },
    },
    {
        name: "blsrq: 1 -> 0",
        code: [0xC4, 0xE2, 0xE0, 0xF3, 0xC8],
        set: { rax: 1n },
        check: { reg: 3, want: 0n },
    },
    {
        // MULX r64a, r64b, r/m64 computes rdx * r/m64: r64a (ModRM.reg) takes
        // the high half, r64b (VEX.vvvv) the low half, and RDX is an implicit
        // source rather than a destination.
        name: "mulxq: 64x64 -> 128",
        code: [0xC4, 0xE2, 0xE3, 0xF6, 0xC8],
        set: { rdx: 0x0123456789ABCDEFn, rax: 0xFEDCBA9876543210n },
        // 0x0123456789ABCDEF * 0xFEDCBA9876543210 = 0x0121FA00AD77D7422236D88FE5618CF0
        check: [
            { reg: 1, want: 0x0121FA00AD77D742n },
            { reg: 3, want: 0x2236D88FE5618CF0n },
        ],
    },
    {
        name: "mulxq: (2^64-1)^2",
        code: [0xC4, 0xE2, 0xE3, 0xF6, 0xC8],
        set: { rdx: M, rax: M },
        check: [
            { reg: 1, want: 0xFFFFFFFFFFFFFFFEn },
            { reg: 3, want: 1n },
        ],
    },
    {
        // SARX: arithmetic shift right, count from VEX.vvvv.
        name: "sarxq: keeps the sign",
        code: [0xC4, 0xE2, 0xFA, 0xF7, 0xCB],
        set: { rbx: 0x8000000000000000n, rax: 4n },
        check: { reg: 1, want: 0xF800000000000000n },
    },

    // ---- RORX -----------------------------------------------------------
    //
    // RORX dominates the VEX instruction mix of the Alpine live boot: about 4
    // million executions, roughly 70% of every VEX instruction the guest
    // issues, because OpenSSL's RSAZ Montgomery multiplication loop is built
    // from it. A wrong RORX therefore corrupts apk's RSA signature check, which
    // is the observed "BAD signature" failure. Hence the wide immediate sweep,
    // both operand sizes, and the count-of-zero case.
    {
        name: "rorxq: imm 5",
        code: [0xC4, 0xE3, 0xFB, 0xF0, 0xD8, 0x05],
        set: { rax: 0x0123456789ABCDEFn },
        check: { reg: 3, want: 0x78091A2B3C4D5E6Fn },
    },
    {
        // A count of 0 must return the source unchanged rather than shifting by
        // the full width.
        name: "rorxq: imm 0",
        code: [0xC4, 0xE3, 0xFB, 0xF0, 0xD8, 0x00],
        set: { rax: 0x0123456789ABCDEFn },
        check: { reg: 3, want: 0x0123456789ABCDEFn },
    },
    {
        // rot 63 == rotl 1, so 0x0123456789ABCDEF << 1 = 0x02468ACF13579BDE.
        name: "rorxq: imm 63",
        code: [0xC4, 0xE3, 0xFB, 0xF0, 0xD8, 0x3F],
        set: { rax: 0x0123456789ABCDEFn },
        check: { reg: 3, want: 0x02468ACF13579BDEn },
    },
    {
        name: "rorxq: imm 32",
        code: [0xC4, 0xE3, 0xFB, 0xF0, 0xD8, 0x20],
        set: { rax: 0x0123456789ABCDEFn },
        check: { reg: 3, want: 0x89ABCDEF01234567n },
    },
    {
        // 32-bit form: W=0, and the result zero-extends into the 64-bit register.
        name: "rorxl: imm 5",
        code: [0xC4, 0xE3, 0x7B, 0xF0, 0xD8, 0x05],
        set: { rax: 0x89ABCDEFn },
        check: { reg: 3, want: 0x7C4D5E6Fn },
    },
    {
        name: "rorxl: imm 0",
        code: [0xC4, 0xE3, 0x7B, 0xF0, 0xD8, 0x00],
        set: { rax: 0x89ABCDEFn },
        check: { reg: 3, want: 0x89ABCDEFn },
    },
    {
        name: "rorxl: imm 31",
        code: [0xC4, 0xE3, 0x7B, 0xF0, 0xD8, 0x1F],
        set: { rax: 0x89ABCDEFn },
        check: { reg: 3, want: 0x13579BDFn },
    },
    {
        // The count is masked to the operand width, so 0x21 is 33, not an
        // out-of-range shift.
        name: "rorxl: imm 33 wraps to 1",
        code: [0xC4, 0xE3, 0x7B, 0xF0, 0xD8, 0x21],
        set: { rax: 0x89ABCDEFn },
        check: { reg: 3, want: 0xC4D5E6F7n },
    },
    {
        // RORX is defined not to modify any flag. If it did, guest code that
        // reads flags after it would branch differently.
        name: "rorxq: leaves the flags alone",
        code: [0xC4, 0xE3, 0xFB, 0xF0, 0xD8, 0x05],
        set: { rax: 0x0123456789ABCDEFn },
        cf: true,
        of: true,
        check: [
            { reg: 3, want: 0x78091A2B3C4D5E6Fn },
            { flag: "cf", want: true },
            { flag: "of", want: true },
        ],
    },

    // ---- the reserved legacy encodings ------------------------------------
    //
    // A reserved encoding must not execute, and the only thing that can prove it
    // here is the destination register: this harness has no IDT, so a #UD becomes
    // a triple fault and a halt, which is indistinguishable from the instruction
    // simply having run. Both outcomes halt, so the halt check proves nothing and
    // the register check is the real assertion.
    //
    // ANDN legacy slot 0F38 F2 with ModRM /3 would compute ~ecx & ebx into edx, so
    // a seeded edx that survives is the only way to tell the two apart.
    ...[
        ["0f 38 f2 d1 (reserved ANDN slot)", [0x0F, 0x38, 0xF2, 0xD1]],
        ["0f 38 f3 d1 (reserved BLSMSK/BLSR/BLSI slot)", [0x0F, 0x38, 0xF3, 0xD1]],
        ["0f 38 f7 d9 (reserved BEXTR slot)", [0x0F, 0x38, 0xF7, 0xD9]],
    ].map(([name, code]) => ({
        // ModRM D1 selects edx as the destination, so a seeded edx that survives
        // is the only way to tell "raised #UD" from "executed". The operands are
        // chosen so that a wrong execution is unmistakable rather than a zero
        // write that could be confused with a fault: read as ANDN, ModRM D1 is
        // ~rcx & rbx = ~0x0F & 0xFF = 0xF0, which is nothing like the sentinel.
        name: name + ": does not execute",
        code,
        set: { rbx: 0xFFn, rcx: 0x0Fn, rdx: 0x5A5A5A5An },
        check: { reg: 2, want: 0x5A5A5A5An },
    })),

    // ---- RDRAND / RDSEED -------------------------------------------------
    //
    // SDM Vol. 2, "Flags Affected", for both instructions: "The CF flag is set
    // according to the result (see the Operation section above). The OF, SF,
    // ZF, AF, and PF flags are set to 0."
    //
    // All five, not just the two that are easiest to think of. The emulator
    // cleared CF and OF and left SF/ZF/AF/PF as the previous instruction had
    // them, so a caller that reads a status register after RDRAND saw flags from
    // an unrelated instruction. Each case below starts with all six set, so
    // clearing all five is the only thing that can produce the expected value.
    //
    // The random value itself is not checkable and is not checked: CF is the
    // only architectural signal for it, and that is what these vectors pin down.
    // The 16/32/64-bit forms are all included because the operand size changes
    // how much of the destination is written, and the register number changes
    // which REX.B bit selects the destination.
    ...[
        ["rdrandq %rax",   [0x48, 0x0F, 0xC7, 0xF0], "rax"],
        ["rdrandl %eax",   [0x0F, 0xC7, 0xF0],       "rax"],
        ["rdrandw %ax",    [0x66, 0x0F, 0xC7, 0xF0], "rax"],
        ["rdseedq %rbx",   [0x48, 0x0F, 0xC7, 0xFB], "rbx"],
        ["rdseedl %ebx",   [0x0F, 0xC7, 0xFB],       "rbx"],
        ["rdseedw %bx",    [0x66, 0x0F, 0xC7, 0xFB], "rbx"],
    ].map(([insn, code, reg]) => ({
        name: insn + ": sets CF and clears OF/SF/ZF/AF/PF",
        code,
        set: { [reg]: 0x0123456789ABCDEFn },
        // The destination's new value is random, so it is not checked; it is
        // named here so the "no other register moved" check below skips it.
        writes: [reg],
        // Start with every arithmetic flag set so a partial clear is visible.
        flags: "all",
        check: [
            { flag: "cf", want: true },
            ...ZEROED_BY_RDRAND.map(f => ({ flag: f, want: false })),
        ],
    })),

    // ---- ADCX / ADOX ----------------------------------------------------
    //
    // ADCX consumes and produces CF; ADOX consumes and produces OF. Getting
    // that backwards makes ADOX look broken when it is not -- which happened
    // while writing these tests.
    {
        name: "adcxq: with CF=1",
        code: [0x66, 0x48, 0x0F, 0x38, 0xF6, 0xC8],
        set: { rax: 0xFFFFFFFFFFFFFFFFn, rcx: 1n },
        cf: true,
        // dst = rcx = rax + rcx + CF = M + 1 + 1 = 1, CF = 1
        check: [{ reg: 1, want: 1n }, { flag: "cf", want: true }],
    },
    {
        name: "adcxq: with CF=0",
        code: [0x66, 0x48, 0x0F, 0x38, 0xF6, 0xC8],
        set: { rax: 5n, rcx: 7n },
        cf: false,
        check: [{ reg: 1, want: 12n }, { flag: "cf", want: false }],
    },
    {
        name: "adoxq: with OF=1",
        code: [0xF3, 0x48, 0x0F, 0x38, 0xF6, 0xC8],
        set: { rax: 0xFFFFFFFFFFFFFFFFn, rcx: 2n },
        of: true,
        check: [{ reg: 1, want: 2n }, { flag: "of", want: true }],
    },
    {
        name: "adoxq: with OF=0",
        code: [0xF3, 0x48, 0x0F, 0x38, 0xF6, 0xC8],
        set: { rax: 100n, rcx: 23n },
        of: false,
        check: [{ reg: 1, want: 123n }, { flag: "of", want: false }],
    },
    {
        // ADCX uses CF and must leave OF alone.
        name: "adcxq: leaves OF alone",
        code: [0x66, 0x48, 0x0F, 0x38, 0xF6, 0xC8],
        set: { rax: 5n, rcx: 7n },
        cf: true,
        of: true,
        check: [{ reg: 1, want: 13n }, { flag: "of", want: true }],
    },
    {
        // ADOX uses OF and must leave CF alone.
        name: "adoxq: leaves CF alone",
        code: [0xF3, 0x48, 0x0F, 0x38, 0xF6, 0xC8],
        set: { rax: 5n, rcx: 7n },
        cf: true,
        of: true,
        check: [{ reg: 1, want: 13n }, { flag: "cf", want: true }],
    },
    {
        // Without REX.W the operation is 32-bit and zero-extends into the
        // 64-bit destination register.
        name: "adcx: 32-bit form zero-extends",
        code: [0x66, 0x0F, 0x38, 0xF6, 0xC8],
        set: { rax: 0xFFFFFFFF00000005n, rcx: 0xFFFFFFFF00000007n },
        cf: false,
        check: [{ reg: 1, want: 12n }],
    },

    // ---- MULX with a memory operand ------------------------------------
    //
    // The register-operand cases above do not touch the memory path, and the
    // memory form is what OpenSSL's RSAZ code uses. MULX is also the single VEX
    // instruction the guest still issues with AVX switched off, so a fault here
    // would survive every CPUID variation tried.
    {
        name: "mulxq: memory multiplicand",
        code: {
            bytes: [0xC4, 0xC2, 0xE3, 0xF6, 0x0F],
            mem: [0xEF, 0xCD, 0xAB, 0x89, 0x67, 0x45, 0x23, 0x01],
        },
        set: { rdx: 0xFEDCBA9876543210n, rcx: 0n },
        check: [
            { reg: 1, want: 0x0121FA00AD77D742n },
            { reg: 3, want: 0x2236D88FE5618CF0n },
        ],
    },
    {
        // Multiplier 1: with RDX = 1 the memory value comes back unchanged in the
        // low half -- VEX.vvvv, reg 3 -- and the high half, ModRM.reg, is zero.
        // This separates a missing or misaligned memory read from a half-swap,
        // and it is also the case where reading the multiplicand from VEX.vvvv
        // instead of RDX still happens to work, which is why the other cases
        // above matter.
        name: "mulxq: memory multiplicand, multiplier 1",
        code: {
            bytes: [0xC4, 0xC2, 0xE3, 0xF6, 0x0F],
            mem: [0xEF, 0xCD, 0xAB, 0x89, 0x67, 0x45, 0x23, 0x01],
        },
        set: { rdx: 1n, rcx: 0n },
        check: [
            { reg: 1, want: 0n },
            { reg: 3, want: 0x0123456789ABCDEFn },
        ],
    },
    {
        // With src1 = 0 the result is just the memory operand, so this
        // separates "the memory read failed" from "~src1 was applied wrongly".
        name: "andnq: memory source, src1 = 0",
        code: {
            // c4 c2 e0 f2 0f. Note the b1 byte: 0xc2 has B-bar set, i.e.
            // REX.B=1, so ModRM.r/m = r15. The near-identical c4 e2 e0 f2 0f
            // is the (%rdi) form and silently reads the wrong register.
            bytes: [0xC4, 0xC2, 0xE0, 0xF2, 0x0F],
            mem: [0xF0, 0x0F, 0xFF, 0xF0, 0x00, 0x00, 0x00, 0x00],
        },
        set: { rbx: 0n, rcx: 0n },
        check: { reg: 1, want: 0xF0FF0FF0n },
    },
    {
        // ANDN with a memory first source.
        name: "andnq: memory source",
        code: {
            // c4 c2 e0 f2 0f. Note the b1 byte: 0xc2 has B-bar set, i.e.
            // REX.B=1, so ModRM.r/m = r15. The near-identical c4 e2 e0 f2 0f
            // is the (%rdi) form and silently reads the wrong register.
            bytes: [0xC4, 0xC2, 0xE0, 0xF2, 0x0F],
            mem: [0xF0, 0x0F, 0xFF, 0xF0, 0x00, 0x00, 0x00, 0x00],
        },
        // Bytes F0 0F FF F0 little-endian are 0x00000000F0FF0FF0, and ~0x0F is
        // 0xFFFFFFFFFFFFFFF0, so the result is 0x00000000F0FF0FF0.
        set: { rbx: 0x0Fn, rcx: 0n },
        check: { reg: 1, want: 0xF0FF0FF0n },
    },

    // ---- MOVSXD (0x63 with REX.W) -------------------------------------
    //
    // These came out of a live crash, not out of inspection. Booting the Alpine
    // live ISO with XSAVE advertised produces
    //   mdev[496]: segfault at 7f0992948710 ... in ld-musl-x86_64.so.1
    //   Code: ... 49 63 46 c8 <49> 63 44 85 00 48 6b c0 38 ...
    // and the marked instruction is REX.W + opcode 0x63, i.e. MOVSXD rax,
    // dword [r13 + rax*4] -- musl's dynamic linker walking a table with a
    // sign-extended 32-bit index. If MOVSXD zero-extends instead of
    // sign-extending, a negative index becomes an enormous positive one and the
    // walk runs off the end, which is exactly the fault above. Widening with
    // MOV instead, or dropping REX.W, produces the same bytes and would not be
    // caught without these cases.
    {
        // movslq (%r15), %rax  ==  49 63 07
        name: "movsxd: memory, negative -> sign extended",
        code: { bytes: [0x49, 0x63, 0x07],
                mem: [0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00] },
        set: { rax: 0n },
        check: { reg: 0, want: 0xFFFFFFFFFFFFFFFFn },
    },
    {
        // 0x80000000 is the case that separates sign extension from zero
        // extension most sharply: zero-extended it is 0x0000000080000000.
        name: "movsxd: memory, 0x80000000",
        code: { bytes: [0x49, 0x63, 0x07],
                mem: [0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00] },
        set: { rax: 0n },
        check: { reg: 0, want: 0xFFFFFFFF80000000n },
    },
    {
        name: "movsxd: memory, small positive",
        code: { bytes: [0x49, 0x63, 0x07],
                mem: [0x01, 0x02, 0x03, 0x04, 0x00, 0x00, 0x00, 0x00] },
        set: { rax: 0n },
        check: { reg: 0, want: 0x04030201n },
    },
    {
        // movslq %eax, %rax  ==  48 63 c0
        name: "movsxd: register, 0x80000000",
        code: [0x48, 0x63, 0xC0],
        set: { rax: 0xFFFFFFFF80000000n },
        check: { reg: 0, want: 0xFFFFFFFF80000000n },
    },
    {
        // movslq 0x8(%r15,%rax,4), %rax  ==  49 63 44 87 08
        // SIB with a scale of 4 and an index, which is the addressing form in
        // the faulting instruction.
        name: "movsxd: SIB, negative index field",
        code: { bytes: [0x49, 0x63, 0x44, 0x87, 0x08],
                mem: [0xFF, 0xFF, 0xFF, 0xFF,   // +0
                      0xAA, 0xAA, 0xAA, 0xAA,   // +4
                      0xEF, 0xBE, 0xAD, 0xDE,   // +8  <- the dword that is read
                      0x00, 0x00, 0x00, 0x00] },
        set: { rax: 0n },
        // MOVSXD sign-extends: the dword 0xDEADBEEF becomes
        // 0xFFFFFFFFDEADBEEF, not 0x00000000DEADBEEF.
        check: { reg: 0, want: 0xFFFFFFFFDEADBEEFn },
    },
    {
        // mov  (%r15), %eax  ==  41 8b 07 -- zero-extending, for contrast: a
        // widening load that must NOT sign-extend.
        name: "mov r32 from memory zero-extends",
        code: { bytes: [0x41, 0x8B, 0x07],
                mem: [0x00, 0x00, 0x00, 0x80, 0xFF, 0xFF, 0xFF, 0xFF] },
        set: { rax: 0n },
        check: { reg: 0, want: 0x0000000080000000n },
    },

];

const emulator = new v64({
    autostart: false,
    memory_size: 8 * 1024 * 1024,
    disable_jit: 0,
    log_level: 0,
    wasm_path: process.env.WASM_PATH || undefined,
});

emulator.add_listener("emulator-loaded", async () =>
{
    const cpu = emulator.v86.cpu;
    const ex = cpu.wm.exports;
    const u32 = new Uint32Array(ex.memory.buffer);
    const ext = new BigUint64Array(ex.memory.buffer, 160, 8);

    const write64 = (a, v) =>
    {
        ex.write32(a, Number(v & 0xFFFF_FFFFn));
        ex.write32(a + 4, Number(v >> 32n & 0xFFFF_FFFFn));
    };
    write64(PML4, BigInt(PDPT) | 0x3n);
    write64(PDPT, BigInt(PD) | 0x3n);
    write64(PD, BigInt(PT) | 0x3n);
    for(let i = 0; i < 512; i++) write64(PT + i * 8, BigInt(i) * 0x1000n | 0x3n);

    const set64 = (i, v) =>
    {
        if(i < 8)
        {
            u32[16 + i] = Number(u64(v) & 0xFFFF_FFFFn);
            u32[32 + i] = Number((u64(v) >> 32n) & 0xFFFF_FFFFn);
        }
        else { ext[i - 8] = u64(v); }
    };
    const get64 = i =>
        (i < 8) ? ((BigInt(u32[32 + i]) << 32n) | BigInt(u32[16 + i])) : ext[i - 8];

    // ---- harness self-check -------------------------------------------
    // Write 16 mutually distinct values, read them back untouched. If any
    // mismatch, every later result is meaningless, so abort instead.
    {
        const distinct = [];
        for(let i = 0; i < 16; i++)
        {
            // Mask to 64 bits: the multiply overflows past i = 0, and an
            // unmasked expectation would make every register but r0 "fail".
            distinct.push(BigInt.asUintN(64, 0x9E3779B97F4A7C15n * BigInt(i + 1)));
        }
        const want4 = 0x80000n;
        for(let i = 0; i < 16; i++) set64(i, distinct[i]);
        set64(4, want4);
        ex.write8(BASE, 0xF4);
        cpu.instruction_pointer[0] = BASE;
        cpu.flags[0] = 0x2;
        cpu.in_hlt[0] = 0;
        ex.enter_long_mode(PML4);
        let g = 0;
        while(!cpu.in_hlt[0] && g++ < 20000) ex.main_loop();
        const bad = [];
        for(let i = 0; i < 16; i++)
        {
            const want = i === 4 ? want4 : distinct[i];
            if(get64(i) !== want)
            {
                bad.push("r" + i + "=0x" + get64(i).toString(16) +
                    " want 0x" + want.toString(16));
            }
        }
        if(bad.length)
        {
            console.log("harness read-back FAILED: " + bad.join(", "));
            console.log("results below would be meaningless; aborting");
            process.exit(2);
        }
        console.log("harness self-check: register read-back ok (16/16 distinct)\n");
    }

    const run = (code, set, jitEnabled, flags) =>
    {
        set_cpu_config(ex, "JIT_DISABLE", jitEnabled ? 0 : JIT_DISABLE_64);
        ex.jit64_clear_cache();
        const bytes = Array.isArray(code) ? code : code.bytes;
        const program = bytes.concat([0xF4]);
        for(let i = 0; i < program.length; i++) ex.write8(BASE + i, program[i]);
        for(let i = 0; i < 16; i++) set64(i, 0n);
        set64(4, 0x80000n);
        // r15 addresses the staging area for the memory-operand cases.
        set64(15, BigInt(SCRATCH));
        if(!Array.isArray(code) && code.mem)
        {
            for(let i = 0; i < code.mem.length; i++)
            {
                ex.write8(SCRATCH + i, code.mem[i] & 0xFF);
            }
        }
        for(const [r, v] of Object.entries(set || {})) set64(REG[r], v);
        // Start from a known flags value so OF cannot leak between cases: ADCX
        // uses CF, ADOX uses OF, and confusing the two is an easy way to
        // invent a failure that is not there.
        cpu.flags[0] = 0x2;
        if(flags === "all")
        {
            // Every arithmetic flag set, so a case that expects them cleared
            // cannot pass by accident through the emulator never touching them.
            for(const f of ARITH_FLAGS) cpu.flags[0] |= FLAG_BIT[f];
        }
        else if(flags)
        {
            if(flags.cf) cpu.flags[0] |= 1;
            if(flags.of) cpu.flags[0] |= (1 << 11);
        }
        cpu.instruction_pointer[0] = BASE;
        cpu.in_hlt[0] = 0;
        ex.enter_long_mode(PML4);
        let g = 0;
        while(!cpu.in_hlt[0] && g++ < 20000) ex.main_loop();
        return { halted: cpu.in_hlt[0] === 1, rip: cpu.instruction_pointer[0] >>> 0 };
    };

    const engines = [];
    const which = process.env.BMI1_ENGINE || "both";
    if(which === "interp" || which === "both") engines.push(["interp", false]);
    if(which === "jit" || which === "both") engines.push(["jit", true]);

    let failures = 0;
    for(const c of CASES)
    {
        const checks = Array.isArray(c.check) ? c.check : [c.check];
        const bad = [];
        for(const [label, jitEnabled] of engines)
        {
            const r = run(c.code, c.set, jitEnabled, c.flags || { cf: c.cf, of: c.of });
            if(!r.halted)
            {
                bad.push(label + ": did not halt (rip=0x" + r.rip.toString(16) + ")");
                continue;
            }
            for(const chk of checks)
            {
                if(chk.flag)
                {
                    const bit = FLAG_BIT[chk.flag];
                    if(bit === undefined)
                    {
                        bad.push(label + ": unknown flag " + chk.flag);
                        continue;
                    }
                    const got = (cpu.flags[0] & bit) !== 0;
                    if(got !== chk.want)
                    {
                        bad.push(label + ": " + chk.flag.toUpperCase() + "=" + got +
                            " want " + chk.want);
                    }
                    continue;
                }
                const got = get64(chk.reg);
                if(got !== chk.want)
                {
                    bad.push(label + ": r" + chk.reg + "=0x" + got.toString(16) +
                        " want 0x" + chk.want.toString(16));
                }
            }
            // BMI1/BMI2/ADX write at most two registers, so any other source
            // that changed means the wrong register was written. An instruction
            // whose destination value is not checkable (RDRAND/RDSEED) lists it
            // in `writes` instead, since there is no expected value to compare.
            for(const [name, idx] of Object.entries(c.set || {}))
            {
                const reg = REG[name];
                if(checks.some(k => k.reg === reg)) continue;
                if((c.writes || []).some(n => REG[n] === reg)) continue;
                if(get64(reg) !== u64(c.set[name]))
                {
                    bad.push(label + ": source " + name + " clobbered (0x" +
                        get64(reg).toString(16) + ")");
                }
            }
        }
        if(bad.length) failures++;
        console.log((bad.length ? "FAIL " : "ok   ") + c.name);
        for(const b of bad) console.log("      " + b);
    }

    console.log("\n" + (failures ? failures + " failing case(s)"
        : "all BMI1/BMI2/ADX/RDRAND/RDSEED/MOVSXD cases match the reference"));
    process.exit(failures ? 1 : 0);
});
